### ISSUE TITLE
comment here

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/all-the-hooks#1]

**Comment by brianamarie** [comment]
gagaga

**Comment by githubteacher** [comment]
adf

**Comment by githubteacher** [comment]
:tada: @brianamarie is now a repository collaborator. :balloon:

**Comment by hollenberry** [comment]
Hello?

**Comment by githubteacher** [comment]
:tada: @hollenberry is now a repository collaborator. :balloon:

**Comment by hollenberry** [comment]
WOW

**Comment by crichID** [comment]
Does this thing work?

**Comment by githubteacher** [comment]
:tada: @crichID is now a repository collaborator. :balloon:

**Comment by brianamarie** [comment]
I suggest you all unsubscribe from this issue because I'm about to spam this during testing 🙇

**Comment by brianamarie** [comment]
moar test

**Comment by brianamarie** [comment]
afaf

**Comment by brianamarie** [comment]
asdf

**Comment by brianamarie** [comment]
afafaf

**Comment by githubteacher** [comment]
wef

**Comment by brianamarie** [comment]
adsf

**Comment by brianamarie** [comment]
asdf

**Comment by brianamarie** [comment]
asdf

**Comment by brianamarie** [comment]
afaafsdf

**Comment by brianamarie** [comment]
floop

**Comment by brianamarie** [comment]
marzipan

**Comment by brianamarie** [comment]
graham cracker

**Comment by brianamarie** [comment]
asdf

**Comment by brianamarie** [comment]
meowth

**Comment by brianamarie** [comment]
lollipop

**Comment by brianamarie** [comment]
as;ldfkj

**Comment by brianamarie** [comment]
afefdc

**Comment by githubteacher** [comment]
:tada: @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, and @brianamarie are now  repository collaborators. :balloon:

**Comment by kylemacey** [comment]
Can it make me a collaborator?

**Comment by githubteacher** [comment]
:tada: @kylemacey is now a repository collaborator. :balloon:

**Comment by brianamarie** [comment]
can it or should it?

**Comment by hectorsector** [comment]
How about me!?

**Comment by githubteacher** [comment]
:tada: @hectorsector is now a repository collaborator. :balloon:

**Comment by brianamarie** [comment]
hhsge

**Comment by githubteacher** [comment]
:tada: @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, and @brianamarie are now  repository collaborators. :balloon:

**Comment by stoe** [comment]
what about me?

**Comment by githubteacher** [comment]
:tada: @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, @brianamarie, and @stoe are now  repository collaborators. :balloon:
